**Note: In Data Science googling is a very important skill. If you find some difficulties to solve the problem, google it and try to find some clues to solve.**

In [1]:
import numpy as np

###`Q-1` Create a null vector of size 10 but the fifth value which is 1.



In [ ]:
#Code here
a = np.zeros(10)
a[4] =1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


###`Q-2` Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [ ]:
#Code here
def shape_avg(a,b):
    x = np.random.random((a,b))
    average  = np.mean(x)
    print(x)
    print("average of array of  ({},{}) is :".format(a,b),average)

In [ ]:
shape_avg(4,3)

[[0.31117592 0.38925779 0.90932883]
 [0.74186247 0.93746152 0.25243007]
 [0.76109516 0.70517635 0.43331079]
 [0.03328037 0.76010181 0.67762831]]
average of array of  (4,3) is : 0.5760091159391917


###`Q-3`Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

Eg.-
```
[[1,1,1,1],
[1,0,0,1],
[1,0,0,1],
[1,1,1,1]]
```

In [ ]:
#Code here
def one_zero_array(a,b):
    """creates an array of shape a,b and fills the borders with 1 and insides with 0
    """
    x = np.ones((a,b))
    #print(a)
    
    print(x)

In [ ]:
one_zero_array(6,7)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


###`Q-4` Create a vector of size 10 with values ranging from 0 to 1, both excluded.


In [ ]:
#Code here
np.linspace(0,1,12,endpoint=True)[1:-1]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

###`Q-5` Can you create a identity mattrix of shape (3,4). If yes write code for it.

In [ ]:
#Code here
x = np.zeros((3,4))
x[0,0]=1
x[2,3]=1
x[1:(3-1),1:(4-1)] = 1
x

array([[1., 0., 0., 0.],
       [0., 1., 1., 0.],
       [0., 0., 0., 1.]])

###`Q-6:` Create a 5x5 matrix with row values ranging from 0 to 4.

In [ ]:
#Code here
z= np.zeros((5,5))
a = np.arange(5)
z + a


array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

###`Q-7:`  Consider a random integer (in range 1 to 100) vector with shape `(10,2)` representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

```
point = np.array([2,3]) 
```


In [ ]:
point = np.array([2,3])
point

array([2, 3])

In [3]:
#code here
a = np.random.randint(1,100,20).reshape(10,2)
x , y = np.atleast_2d(a[:,0],a[:,1])
point = np.array([2,3])
distance =(np.sqrt( x-point[0]**2 + y-point[1]**2))
print(np.int64(distance))

[[ 8 10  7  9  9  9  9  5 10 11]]


###`Q-8:` Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [ ]:
#Code here

print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


### `Q-9:` Arrays

You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.



**Input Format:**

A single line of input containing space separated numbers.

**Output Format:**

Print the reverse NumPy array with type float.

**Example 1:**

Input:

```bash
1 2 3 4 -8 -10
```

Output:

```bash
[-10.  -8.   4.   3.   2.   1.]
```

In [13]:
#Code here
def array():
  x = input("enter space separted numbers: ")
  arr = x.strip().split(" ")
  return np.array(arr[::-1],float)

In [14]:
array()

enter space separted numbers: 1 2 3 4 -8 -10


array([-10.,  -8.,   4.,   3.,   2.,   1.])

### `Q-10:` Elements count

Count the number of elements of a numpy array.



**Example 1:**

Input:
```bash
np.array([])
```

Output:
```bash
elements_count :  0
```

**Example 2:**

Input:
```bash
np.array([1, 2])
```

Output:
```bash
elements_count :  2
```

In [24]:
#Code here
arr = np.array([1,2])
count = 0
for i in arr:
  count+=1
print("element_count:",count)

element_count: 2


### `Q-11:` Softmax function

Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

$$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=i}^{K}{e^{z_j}}}$$

https://en.wikipedia.org/wiki/Softmax_function



**Example 1:**

Input:
```bash
[86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318]
```

Output:
```bash
[2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01, 
       5.05514197e-22, 1.50974911e-22]
```

**Example 2:**

Input:
```bash
[33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278]
```

Output:
```bash
[4.57181035e-26, 1.16249923e-20, 7.73872596e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01]
```

In [66]:
#Code here
def softmax():
    """calcultates the softmax of a given 1D array
    """
    x= input("provide a space separated list")
    l = list(x.strip("[ ]").split(" "))
    L = []
    for i in l:
        try:
            L.append(float(i))
        except:
            continue
    arr = np.array(L)
    if arr.ndim == 1:
        return np.exp(arr)/np.sum(np.exp(arr),axis=0)
    else:
        print("please provide an array with 1 dimension")



In [70]:
softmax()

array([4.57181033e-26, 1.16249922e-20, 7.73872594e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01])

### `Q-12:` Vertical stack

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.



**Example 1:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]
```

Output:

```bash
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
```

**Example 2:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]

c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]] 
```

Output:
```bash
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

In [49]:
#Coder here

def v_stack(*args):
        try:    
            print(np.vstack((list(args))))
        except:
            print("please enter a valid numpy array of equal size")




In [48]:
a= [[0,1,2 ,3, 4],
 [5, 6, 7, 8, 9]]

b= [[1, 1, 1, 1, 1],
 [1, 1, 1, 1, 1]]

c= [[0.10117373, 0.1677244,  0.73764059, 0.83166097, 0.48985695],
 [0.44581567, 0.13502419, 0.55692335, 0.16479622, 0.61193593]] 
v_stack(a,b)

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [50]:
v_stack(np.array([1,2,3]),np.array([3,4,5]))

[[1 2 3]
 [3 4 5]]


### `Q-13:` Dates

Create a python function named **date_array** that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: `2022-12-6`. The end date should be included and for simplicity, choose dates from a same year.



**Example 1:**

Input:
```bash
date_array(start = '2020-09-15', end = '2020-09-25')
```

Output:
```bash
['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
 '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
 '2020-09-23', '2020-09-24', '2020-09-25']
```

**Example 2:**

Input:
```bash
date_array(start = '2022-12-01', end = '2022-12-06')
```

Output:
```bash
['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06']
```

**Example 3:**

Input:
```bash
date_array(start = '2020-11-25', end = '2020-11-30')
```

Output:
```bash
['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
 '2020-11-29', '2020-11-30']
```

In [32]:
#Code here
def date_array(start,end):
    if type(start) == str and type(end) == str:
        end = np.datetime64(end) + np.timedelta64(1,'D')
        arr = np.arange(start,end,dtype='datetime64[D]')
        return arr
    else:
        print("please enter date in string format")

In [40]:
date_array(start = '2020-11-25', end = '2020-11-30')

array(['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
       '2020-11-29', '2020-11-30'], dtype='datetime64[D]')

###`Q-14:` Subtract the mean of each row from a matrix.

In [8]:
#code here
a = np.arange(12).reshape(3,4)
print(a)
a  - a.mean(axis=1,keepdims=True)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[-1.5, -0.5,  0.5,  1.5],
       [-1.5, -0.5,  0.5,  1.5],
       [-1.5, -0.5,  0.5,  1.5]])

###`Q-15:` Swap column-1 of array with column-2 in the array.

In [16]:
#Code here
a = np.arange(12).reshape(3,4)
print(a)
a[:,[0,1]] = a[:,[1,0]]
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 1  0  2  3]
 [ 5  4  6  7]
 [ 9  8 10 11]]


###`Q-16:` Replace odd elements in arrays with -1.

In [29]:
#Code here
a= np.arange(25).reshape(5,5)
a[a%2!=0] = -1
print(a)

[[ 0 -1  2 -1  4]
 [-1  6 -1  8 -1]
 [10 -1 12 -1 14]
 [-1 16 -1 18 -1]
 [20 -1 22 -1 24]]


###`Q-17:` Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
```
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

Result-> [6 3 1 7 8]
``` 

In [32]:
#Code here
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])
c = np.maximum(a,b)
print("Results ->",c)

Results -> [6 3 1 7 8]


###`Q-18` Answer below asked questions on given array:
1. Fetch Every alternate column of the array
2. Normalise the given array

https://en.wikipedia.org/wiki/Normalization_(statistics)

There are different form of normalisation for this question use below formula.

$$\large X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

```python
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
```


In [33]:
# Given
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
arr1

array([[ 161, 8948,  743,   26, 1653],
       [7518, 7774, 3137, 4695, 6721],
       [1368, 2733, 4497, 3805, 5637],
       [9005, 1199, 9300, 1363, 9535],
       [3643, 8372, 6672, 9965, 5400],
       [9333, 8872,  840, 7244, 7114],
       [7225, 8490, 6861, 1902, 3881],
       [3458, 3447, 5604, 6900, 5672]])

In [36]:
#Code here
Xn = (arr1 - arr1.min())/(arr1.max() - arr1.min())
print(Xn)

[[0.01358286 0.89767582 0.07214005 0.         0.16369856]
 [0.75379817 0.77955529 0.31300936 0.46976557 0.67360901]
 [0.13502364 0.2723614  0.44984405 0.38021934 0.56454372]
 [0.90341081 0.11801992 0.93309186 0.13452058 0.95673609]
 [0.36391991 0.83972231 0.66867894 1.         0.54069826]
 [0.93641211 0.89002918 0.08189959 0.72623    0.71315022]
 [0.72431834 0.85159473 0.68769494 0.18875138 0.38786598]
 [0.34530637 0.34419962 0.56122346 0.69161888 0.5680652 ]]


###`Q-19:` Write a function which will accept 2 arguments.
First: A 1D numpy array arr

Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array
```
# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40
```

In [57]:
#Code here
arr=(12,34,40,7,1,0) 
n=3
sorted(arr)[n]
np.ndim(arr)

def n_largest(arr,num):
    if type(num) != int:
        print("Please provide a integer")
    elif num > len(arr):
        print("Please provide an integer less than the length of the array")
    elif np.ndim(arr) != 1:
        print("Please provide a 1D array")
    else:
        print("nth largest element is", sorted(arr)[-num])

In [59]:
n_largest((12,34,40,7,1,0),3)

nth largest element is 12


###`Q-20:` Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
```
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [74]:
#code here
a = np.array([1,2,3])
b = np.repeat(a,3)
c = np.tile(a,3)
np.concatenate((b,c))

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])